language: php

php:
  - '7.4'

before_script:
  - sudo apt-get update
  - php --ri zip
  - php --ri gd
  - php --ri curl
  - php --ri sqlite3
  - php --ri xml
  - php --ri mbstring
  - sudo apt-get install ca-certificates curl xz-utils git

script:
  - php --version
  - phpunit --version
  - env