language: php

php:
  - '7.4'

env:
  global:
    - NEXTCLOUD_DB=sqlite
    - NEXTCLOUD_DB_NAME=nextcloud
    - NEXTCLOUD_DB_USER=root
    - NEXTCLOUD_DB_PASSWD=password
    - NEXTCLOUD_ADMIN_NAME=admin
    - NEXTCLOUD_ADMIN_PASSWD=password

before_script:
  - sudo apt-get update
  - php --ri zip
  - php --ri gd
  - php --ri curl
  - php --ri sqlite3
  - php --ri xml
  - php --ri mbstring
  - sudo apt-get install ca-certificates curl xz-utils git
  - git clone https://github.com/nextcloud/server.git
  - mv server/ nextcloud
  - cd nextcloud
  - git checkout origin/stable19 -b stable19
  - mkdir custom_apps
  - cp -pi ${TRAVIS_BUILD_DIR}/travis/apps.config.php config
  - cd 3rdparty
  - git submodule update --init
  - cd ..
  - php occ maintenance:install --database ${NEXTCLOUD_DB} --database-name ${NEXTCLOUD_DB_NAME} --database-user ${NEXTCLOUD_DB_USER} --database-pass ${NEXTCLOUD_DB_PASSWD} --admin-user ${NEXTCLOUD_ADMIN_NAME} --admin-pass ${NEXTCLOUD_ADMIN_PASSWD}
  - cp -r ${TRAVIS_BUILD_DIR}/file-update-notifications custom_apps/
  - php occ app:enable file-update-notifications

script:
  - php --version
  - phpunit --version
  - env